base_controller:
  type: "robot_controllers/DiffDriveBaseController"
  max_velocity_x: 1.5
  max_acceleration_x: 1.25
  # hold position
  moving_threshold: -0.01
  rotating_threshold: -0.01
  # autostart to get odom
  autostart: true

robot_driver:
  default_controllers:
    - "base_controller"
